--<ScriptOptions statementTerminator=";"/>

CREATE TABLE PRODUCT_STORE (
		ID INTEGER NOT NULL,
		AVAILABLEITEMS INTEGER NOT NULL,
		COST INTEGER NOT NULL,
		DESCRIPTION VARCHAR(255) NOT NULL,
		ITEMNAME VARCHAR(255) NOT NULL
	);

CREATE UNIQUE INDEX PRIMARY_KEY_4 ON PRODUCT_STORE (ID ASC);

ALTER TABLE PRODUCT_STORE ADD CONSTRAINT CONSTRAINT_4 PRIMARY KEY (ID);

